### ISSUE TITLE
Up to date modifications

### ISSUE THREAD

**Issue by MeloHenrique** [peterwishart/kafka-dockeree#2]
Hello,

First off, thanks for all the hard work you've put into this! I get that in a perfect world, Kafka would be running on Linux with or without Docker. But let's face it, sometimes that's just not possible without spending a ton of time migrating and configuring other stuff.

In my case, I can't justify spending all that time to migrate everything right now. One of my servers doesn't even support Hyper-V, which means no Linux subsystems, and installing a bare-metal Linux distro would be a pretty big change for the client.

So, I think it makes sense to keep this up-to-date and maybe even publish the images to Docker Hub. I've made some modifications to the script (and removed Kafka-Manager), but if you want to keep it, just let me know and I'll create a PR.

**Comment by peterwishart** [comment]
Hi Henrique - glad this was useful! 
If you have changes you want to PR that's fine with me.

**Comment by MeloHenrique** [comment]
#3 You can check my PR and let me know if there's anything wrong or missing.
